default: &default
  host: localhost
  username: <%= Rails.application.secrets.username %>
  password: <%= Rails.application.secrets.password %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: macromeal_development

test:
  <<: *default
  database: macromeal_test

production:
  <<: *default
  database: macromeal_production
  username: macromeal
  password: <%= ENV['MACROMEAL_DATABASE_PASSWORD'] %>
