default: &default
  host: localhost
  username: kashir
  password: th3mmpwd
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: macromeal_development

test:
  <<: *default
  database: macromeal_test

production:
  <<: *default
  database: macromeal_production
  username: macromeal
  password: <%= ENV['MACROMEAL_DATABASE_PASSWORD'] %>
