# Product.create(name: 'Pechuga de pollo', category: 'carne', img: 'pechuga_pollo.jpg', calories: 86, protein: 23, fat: 1, carbs: 0, price: 0.60)
# Product.create(name: 'Muslo de pollo', category: 'carne', img: 'muslo_pollo.jpg', calories: 109, protein: 21, fat: 2, carbs: 0, price: 0.65)
# Product.create(name: 'Filete de cerdo', category: 'carne', img: 'filete_cerdo.jpg', calories: 190, protein: 19, fat: 12, carbs: 0, price: 0.45)
# Product.create(name: 'Chuleta de cerdo', category: 'carne', img: 'chuleta_cerdo.jpg', calories: 198, protein: 19, fat: 13, carbs: 0, price: 0.55)
# Product.create(name: 'Solomillo de cerdo', category: 'carne', img: 'solomillo_cerdo.jpg', calories: 112, protein: 21, fat: 2, carbs: 0, price: 0.70)
# Product.create(name: 'Filete de ternera', category: 'carne', img: 'filete_ternera.jpg', calories: 98, protein: 21, fat: 3, carbs: 0, price: 1.10)
# Product.create(name: 'Chuleta de ternera', category: 'carne', img: 'chuleta_ternera.jpg', calories: 118, protein: 21, fat: 3, carbs: 0, price: 1.20)
# Product.create(name: 'Paletilla de cordero', category: 'carne', img: 'paletilla_cordero.jpg', calories: 314, protein: 16, fat: 28, carbs: 0, price: 1.50)
# Product.create(name: 'Costilla de cordero', category: 'carne', img: 'costilla_cordero.jpg', calories: 385, protein: 12, fat: 37, carbs: 0, price: 1.30)
# Product.create(name: 'Chuleta de cordero', category: 'carne', img: 'chuleta_cordero.jpg', calories: 199, protein: 19, fat: 13, carbs: 0, price: 1.20)
# ---
# Product.create(name: 'Lenguado', category: 'pescado', img: 'lenguado.jpg', calories: 87, protein: 17, fat: 1, carbs: 0, price: 0.80)
# Product.create(name: 'Bacalao', category: 'pescado', img: 'bacalao.jpg', calories: 79, protein: 18, fat: 0, carbs: 0, price: 0.85)
# Product.create(name: 'Merluza', category: 'pescado', img: 'merluza.jpg', calories: 81, protein: 17, fat: 1, carbs: 0, price: 1.05)
# Product.create(name: 'Rodaballo', category: 'pescado', img: 'rodaballo.jpg', calories: 87, protein: 17, fat: 2, carbs: 0, price: 1.30)
# Product.create(name: 'Besugo', category: 'pescado', img: 'besugo.jpg', calories: 118, protein: 17, fat: 6, carbs: 0, price: 1.20)
# Product.create(name: 'Dorada', category: 'pescado', img: 'dorada.jpg', calories: 102, protein: 22, fat: 2, carbs: 0, price: 0.90)
# Product.create(name: 'Trucha', category: 'pescado', img: 'trucha.jpg', calories: 108, protein: 20, fat: 3, carbs: 0, price: 0.85)
# Product.create(name: 'Atún', category: 'pescado', img: 'atun.jpg', calories: 232, protein: 21, fat: 16, carbs: 0, price: 0.75)
# Product.create(name: 'Boquerones', category: 'pescado', img: 'boquerones.jpg', calories: 107, protein: 20, fat: 2, carbs: 0, price: 0.65)
# Product.create(name: 'Caballa', category: 'pescado', img: 'caballa.jpg', calories: 187, protein: 19, fat: 12, carbs: 0, price: 0.70)
# ---
